NO-137-FieldTooltips
joyfill/components-ios pull request #17
Opened 2023-08-22 06:09 UTC by nishantKumar9408

- Field Tooltips

Loom Video:
https://www.loom.com/share/4afc540cd87a4b6593bd9a790942f695?sid=29f1e92c-778d-48c5-b24f-216476c93e8d

2023-08-24 18:20 UTC, jeremypagley requested changes
@nishantKumar9408 hey man! Below are things I saw and thought it would be better as one comment.

1. I see that you made it like the design but we actually decided to go with using the native system Alert message with the tooltips title, description and just a "dismiss" button. Please jump on a quick call with Sai and he'll explain. He is doing this for react-native
2. I see that the tooltip has the same code per file. There has to be a way to make it a reusable class where you can then trigger that global class from each field.

2023-08-25 02:53 UTC, sayo96 commented
Hey Nishant, like Jeremy mentioned above we are going to use a native alert for the field tooltips. 

- The alert will appear when the user presses the field tooltip icon and it will have the tooltip title, and description along with the dismiss button.

https://github.com/joyfill/components-ios/assets/26695583/b98c404f-b280-4fdf-b0ad-3fd6936b0dc6

Feel free to hit me up if you have any doubts 👍

2023-09-03 22:46 UTC, jeremypagley commented
@nishantKumar9408 Looks great just make sure to use an outlined icon like in the design not a colored filled icon

2023-09-06 00:51 UTC, jeremypagley approved these changes

2023-09-06 12:04 UTC, merged